pipeline {
	agent {
		kubernetes {
			label "java"
		}
	}

	environment {
		ANT_OPTS = "-Xmx2560m"
		LABEL_BUILD_DATE = "${sh(script: "date -u +%Y-%m-%dT%H:%M:%SZ", returnStdout: true).trim()}"
		IMAGE_NAME = "liferay/com-liferay-osb-faro"
		IMAGE_TAG_SUFFIX = "${sh(script: "date +%Y%m%d", returnStdout: true).trim()}-${sh(script: "git rev-parse --short=7 ${GIT_COMMIT}", returnStdout: true).trim()}"
		JAVA_HOME = "/opt/java/jdk8u292-b10"

		DOCKER_BUILD_ARGS = "--build-arg LABEL_BUILD_DATE=${LABEL_BUILD_DATE} --build-arg LABEL_VCS_REF=${GIT_COMMIT} --no-cache -f ./Dockerfile ./"
	}

	stages {
		stage("Build") {
			steps {
				withCredentials([[$class: 'StringBinding', credentialsId: 'analytics_cloud_ci_ssh', variable: 'SECRET']]) {
					sh 'ant setup-sdk'
					sh 'mkdir ~/.ssh'
					sh 'touch ~/.ssh/known_hosts'
					sh 'ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts'
					sh 'eval "$(ssh-agent -s)"'
					sh 'touch ~/.ssh/id_ed25519'
					sh 'echo "ssh private key: $SECRET"'
					sh 'echo $SECRET > ~/.ssh/id_ed25519'
					sh 'ssh-add ~/.ssh/id_ed25519'
					sh 'ant setup-profile-dxp'
					sh 'ant compile install-portal-snapshots'
					sh 'cd modules/dxp/apps/osb/osb-faro'
					sh '../../../../../gradlew copyCloudResources'
                }
			}
		}

		stage("Build Docker Image") {
			steps {
				dir("modules/dxp/apps/osb/osb-faro/osb-faro-docker/cloud") {
					script {
						withDockerRegistry([credentialsId: "dockerhub", url: ""]) {
							osbFaroImage = docker.build(
								"${IMAGE_NAME}-${IMAGE_TAG_SUFFIX}",
								"${DOCKER_BUILD_ARGS}")

                            osbFaroImage.push()
                        }
					}
				}
			}
		}
	}
}