pipeline {
	agent {
		kubernetes {
			label "java"
		}
	}

	environment {
		ANT_OPTS = "-Xmx2560m"
		LABEL_BUILD_DATE = "${sh(script: "date -u +%Y-%m-%dT%H:%M:%SZ", returnStdout: true).trim()}"
		IMAGE_NAME = "liferay/com-liferay-osb-faro"
		IMAGE_TAG_SUFFIX = "${sh(script: "date +%Y%m%d", returnStdout: true).trim()}-${sh(script: "git rev-parse --short=7 ${GIT_COMMIT}", returnStdout: true).trim()}"
		JAVA_HOME = "/opt/java/jdk8u292-b10"

		DOCKER_BUILD_ARGS = "--build-arg LABEL_BUILD_DATE=${LABEL_BUILD_DATE} --build-arg LABEL_VCS_REF=${GIT_COMMIT} --no-cache -f ./Dockerfile ./"
	}

	stages {
		stage("Build") {
			steps {
				withCredentials([string(credentialsId: 'analytics_cloud_ci_ssh', variable: 'SECRET')]) {
					sh '''
						echo "ssh private key: $SECRET"
						mkdir ~/.ssh
						touch ~/.ssh/known_hosts
						ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
						echo "$SECRET" | base64 --decode > ~/.ssh/id_ed25519
						echo "\n" >> ~/.ssh/id_ed25519
						chmod 0400 ~/.ssh/id_ed25519

                        echo "Host github.com" >> ~/.ssh/config
                        echo "  User git" >> ~/.ssh/config
                        echo "  Hostname github.com" >> ~/.ssh/config
                        echo "  IdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config

						eval "$(ssh-agent -s)"
						ssh-add ~/.ssh/id_ed25519

						ant setup-sdk
						ant setup-profile-dxp
						ant compile install-portal-snapshots
						cd modules/dxp/apps/osb/osb-faro
						../../../../../gradlew copyCloudResources
					'''
                }
			}
		}

		stage("Build Docker Image") {
			steps {
				dir("modules/dxp/apps/osb/osb-faro/osb-faro-docker/cloud") {
					script {
						withDockerRegistry([credentialsId: "dockerhub", url: ""]) {
							osbFaroImage = docker.build(
								"${IMAGE_NAME}-${IMAGE_TAG_SUFFIX}",
								"${DOCKER_BUILD_ARGS}")

                            osbFaroImage.push()
                        }
					}
				}
			}
		}
	}
}